### ISSUE TITLE
Warm pool powershell script is not working when it is in Userdata

### ISSUE THREAD

**Issue by itsmurali** [aws-samples/amazon-ec2-auto-scaling-group-examples#5]
Hi there! I see that warm pool instances are getting stuck at Warmed:Pending:Wait instead of Warmed:Stopped.

![image](https://user-images.githubusercontent.com/12543677/123790124-9a2d8f00-d8fb-11eb-85b3-9061c32bda0d.png)

1. Server 1 that ends with 81a7 also got stuck at `Warmed:Pending:Wait`, I RDP in to that instance and ran following powershell -- it immediately turns to `Warmed:Stopped`
2. But same script is not working in Userdata, any thoughts?

**Script that I’m using to change instance lifecycle:**
`Complete-ASLifecycleAction -LifecycleHookName rp-asg-instance-start-hook -AutoScalingGroupName $asgName -LifecycleActionResult CONTINUE -InstanceId $instanceId`

**Below is the error I see in UserdataExecution.log:**
```
2021/06/27 17:16:59Z: Message: The errors from user scripts: Complete-ASLifecycleAction : No active Lifecycle Action found with instance ID i-0cab4a49b4775f908
At C:\server-setup\config\setup-v2.ps1:271 char:2
+     Complete-ASLifecycleAction -LifecycleHookName rp-asg-instance ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...cleActionCmdlet:CompleteASLifecycleActionCmdlet) [Complete-ASLifecycleAction], InvalidOperationException
    + FullyQualifiedErrorId : Amazon.AutoScaling.AmazonAutoScalingException,Amazon.PowerShell.Cmdlets.AS.CompleteASLif
   ecycleActionCmdlet
```

**Comment by horsfieldsa** [comment]
Hello, thanks for reporting this issue. I am unable to reproduce it, so I wanted to check with you on a few things.

1. It takes a few minutes for the instance to transition when instances are launched into service from outside of the warm pool, and into the warm pool (the user-data execution sleeps for 120 seconds to simulate application configuration time that only happens on first boot). How long did you wait to see if it transitioned to a Stopped state?
2. If the above isn't the issue, can you add the full output of the user-data execution logs to this issue? Here's more info on pulling those logs: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-user-data.html#user-data-execution. It'd be best if you could launch a new instance, wait for about 10 minutes, and then pull the log (so we can make sure there was no conflict with you manually stopping the lifecycle hook).
3. Which Windows example did you run (multi-reboot or use the user-data-windows example).

Thanks, Scott.

**Comment by itsmurali** [comment]
Hi @horsfieldsa --
1. Initially I didn't understand so waited for hours and found that it was killing and restarting the instance. Let me try one more time on this one and get back to you
2. Sure, I'll share new logs
3. I tried this in my real use case, where I already have a userdata to execute on launch
